export default () => ({
  PORT: 3003,

  INCLUDE_TESTING_MODULE: true,
  SKIP_PASSWORD_CHECK: true,

  JWT_EXPIRES_IN: 600,

  JWT_REFRESH_EXPIRES_IN: 900,

  EMAIL_CONFIRMATION_EXPIRATION: 10,
  PASSWORD_RECOVERY_EXPIRATION: 10,

  LIMIT_WINDOW_SECONDS: 12,
  MAX_REQUESTS: 10,

  BCRYPT_SALT_ROUNDS: 10,

  THROTTLE_LIMIT: 5,
  THROTTLE_TTL: 10000,
});
